 
export interface PDFsetup { 
    byPort: boolean,
    seaPassage: boolean,
    ECA: boolean,
    pilotageInbound: boolean,
    pilotageOutbound: boolean,
    loading: boolean,
    discharging: boolean,
    tankCleaning: boolean,
    shifting: boolean,
    laybyBerth: boolean,
    bunkering: boolean,
    anchoring: boolean,
    drifting: boolean,
    canalTransit: boolean,
    expectedTime: boolean,
    ladden: boolean,
    cargo: boolean,
    robDO: boolean,
    robFO: boolean,
    restockFO: boolean,
    restockDO: boolean,
    agency: boolean,
}
